### PR TITLE
Improve release card layout

### LINKED ISSUE #46: Download has bad skeuomorphism
"View On Github" should be changed to a text hyperlink so people are less likely to default to that

And then the actual OS "buttons" should have a border on them that makes them look clickable instead.

### PR DESCRIPTION
**Pull request by InfinityGhost**
Closes #46

image

### CODE REVIEW

**Comment by Sublimelime** [comment]
A bit better, but I saw somewhere that a box or background should be put behind each of the 3 OS buttons to more clearly indicate they're links to be clicked (and not just "we support these 3" images) and agree with that.

**Review by jamesbt365 — APPROVED** [review]

**Comment by InfinityGhost** [comment]
> A bit better, but I saw somewhere that a box or background should be put behind each of the 3 OS buttons to more clearly indicate they're links to be clicked (and not just "we support these 3" images) and agree with that.

As for the goal for improving the layout to be less confusing to those who are less technically inclined, this is fine enough. However I do agree something needs done to make it more obvious that they are clickable (I was fine with the link underline for because of this reason)

**Review by gonX — CHANGES_REQUESTED** [review]
image

I was thinking more in the lines of this (except not shit), most importantly buttons being obvious buttons (or change to classic hyperlinks) and the "View on Github" link being significantly less eye catching

**Comment by InfinityGhost** [comment]
> I assume this is getting dropped now that the front page looks different?

For the most part, yes. Closing this.

**Pull request closed without merging**
